// Format:
// CFG( name, scfgType, cppType )

// There is limited information available on this because the TitleData3 struct was not compiled into the PC version.
// This is entirely guesswork based on SteamDB stats, and may be wrong.
// "scfgType" doesn't appear to be used in any code we have, so I've left it as 0.
CFG( version, 0, uint32 )
CFG( joy_pitchsensitivity, 0, float )
CFG( joy_yawsensitivity, 0, float )
CFG( joy_cfg_preset, 0, uint32 )
CFG( joy_cfg_custom_bindingsA, 0, uint32 )
CFG( joy_cfg_custom_bindingsB, 0, uint32 )
