// Format:
// CFG( name, scfgType, cppType )

// There is limited information available on this because the TitleData3 struct was not compiled into the PC version.
// This is entirely guesswork based on SteamDB stats, and may be wrong.
// "scfgType" doesn't appear to be used in any code we have, so I've left it as 0.
CFG( version, 0, uint32 )
CFG( volume, 0, float )
CFG( snd_musicvolume, 0, float )
CFG( mat_monitorgamma, 0, float )
CFG( cloud_saves, 0, uint32 )
CFG( ss_splitmode, 0, uint32 )