// Format:
// CFG( mapname, course, index, total )
//
// Courses are numbered starting from 1 and correspond directly to Xbox context values
// Level index and total are per-course, or both 0 for extra maps (hub etc.)

// Calibration Course
CFG( mp_coop_start,                1, 0, 0 )

// Old Hub
CFG( mp_coop_lobby_2,              2, 0, 0 )

// Course 1 - Team Building
CFG( mp_coop_doors,                3, 1, 6 )
CFG( mp_coop_race_2,               3, 2, 6 )
CFG( mp_coop_laser_2,              3, 3, 6 )
CFG( mp_coop_rat_maze,             3, 4, 6 )
CFG( mp_coop_laser_crusher,        3, 5, 6 )
CFG( mp_coop_teambts,              3, 6, 6 )

// Course 2 - Mass and Velocity
CFG( mp_coop_fling_3,              4, 1, 8 )
CFG( mp_coop_infinifling_train,    4, 2, 8 )
CFG( mp_coop_come_along,           4, 3, 8 )
CFG( mp_coop_fling_1,              4, 4, 8 )
CFG( mp_coop_catapult_1,           4, 5, 8 )
CFG( mp_coop_multifling_1,         4, 6, 8 )
CFG( mp_coop_fling_crushers,       4, 7, 8 )
CFG( mp_coop_fan,                  4, 8, 8 )

// Course 3 - Hard Light Surfaces
CFG( mp_coop_wall_intro,           5, 1, 8 )
CFG( mp_coop_wall_2,               5, 2, 8 )
CFG( mp_coop_catapult_wall_intro,  5, 3, 8 )
CFG( mp_coop_wall_block,           5, 4, 8 )
CFG( mp_coop_catapult_2,           5, 5, 8 )
CFG( mp_coop_turret_walls,         5, 6, 8 )
CFG( mp_coop_turret_ball,          5, 7, 8 )
CFG( mp_coop_wall_5,               5, 8, 8 )

// Course 4 - Excursion Funnels
CFG( mp_coop_tbeam_redirect,       6, 1, 9 )
CFG( mp_coop_tbeam_drill,          6, 2, 9 )
CFG( mp_coop_tbeam_catch_grind_1,  6, 3, 9 )
CFG( mp_coop_tbeam_laser_1,        6, 4, 9 )
CFG( mp_coop_tbeam_polarity,       6, 5, 9 )
CFG( mp_coop_tbeam_polarity2,      6, 6, 9 )
CFG( mp_coop_tbeam_polarity3,      6, 7, 9 )
CFG( mp_coop_tbeam_maze,           6, 8, 9 )
CFG( mp_coop_tbeam_end,            6, 9, 9 )

// Course 5 - Mobility Gels
CFG( mp_coop_paint_come_along,     7, 1, 8 )
CFG( mp_coop_paint_redirect,       7, 2, 8 )
CFG( mp_coop_paint_bridge,         7, 3, 8 )
CFG( mp_coop_paint_walljumps,      7, 4, 8 )
CFG( mp_coop_paint_speed_fling,    7, 5, 8 )
CFG( mp_coop_paint_red_racer,      7, 6, 8 )
CFG( mp_coop_paint_speed_catch,    7, 7, 8 )
CFG( mp_coop_paint_longjump_intro, 7, 8, 8 )

// Credits
CFG( mp_coop_credits,              8, 0, 0 )

// DLC Course - Art Therapy
CFG( mp_coop_separation_1,         9, 1, 9 )
CFG( mp_coop_tripleaxis,           9, 2, 9 )
CFG( mp_coop_catapult_catch,       9, 3, 9 )
CFG( mp_coop_2paints_1bridge,      9, 4, 9 )
CFG( mp_coop_paint_conversion,     9, 5, 9 )
CFG( mp_coop_bridge_catch,         9, 6, 9 )
CFG( mp_coop_laser_tbeam,          9, 7, 9 )
CFG( mp_coop_paint_rat_maze,       9, 8, 9 )
CFG( mp_coop_paint_crazy_box,      9, 9, 9 )

// New Hub + Unused Community Hub
// These share their course number with the original hub, but are located after Art Therapy internally
CFG( mp_coop_lobby_3,              2, 0, 0 )
CFG( mp_coop_community_hub,        2, 0, 0 )